input {
  kafka {
    bootstrap_servers => "kafka:9092"
    topics => ["application-logs"]
    codec => "json"
  }
}

filter {

  json {
    source => "message"
  }

  mutate {
    remove_field => ["message"]
  }

}

output {

  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "application-logs"
  }

  stdout {
    codec => rubydebug
  }

}